version: 2

run:
  tests: false     

linters:
  fast: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - paralleltest
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - thelper
    - unconvert
    - unparam
    - unused
    - wsl
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  funlen:
    lines: 65
    statements: 40
  gocognit:
    min-complexity: 15
  gocyclo:
    min-complexity: 10
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
      - hugeParam
      - whyNoLint
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
  misspell:
    locale: US
  nestif:
    min-complexity: 4
  nolintlint:
    require-explanation: false
    require-specific: true

formatters:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: ikakbolit
  gci:
    sections:
      - standard
      - default
      - prefix(ikakbolit)

issues:
  exclude-dirs:
    - docs
    - example
    - proto
    - go/pkg/mod

output:
  sort-results: true
  print-linter-name: true
  print-issued-lines: true
  format: tab