volumes:
  postgres_volume:

services:
  postgres:
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSL=${POSTGRES_SSL}
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    restart: on-failure