version: "3.9"

volumes:
  postgres_volume:


services:
  postgres:
    image: postgis/postgis:16-3.4
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SSL=${POSTGRES_SSL}
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    restart: on-failure

  ikakbolit:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    environment:
      - POSTGRES_DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL}

    depends_on:
      - postgres

    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure
