// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ControllerResponseScheduleID controller response schedule ID
//
// swagger:model controller.responseScheduleID
type ControllerResponseScheduleID struct {

	// schedule id
	ScheduleID string `json:"schedule_id,omitempty"`
}

// Validate validates this controller response schedule ID
func (m *ControllerResponseScheduleID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this controller response schedule ID based on context it is used
func (m *ControllerResponseScheduleID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerResponseScheduleID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerResponseScheduleID) UnmarshalBinary(b []byte) error {
	var res ControllerResponseScheduleID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
