// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ControllerSchedule controller schedule
//
// swagger:model controller.Schedule
type ControllerSchedule struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// cure name
	CureName string `json:"cure_name,omitempty"`

	// doses per day
	DosesPerDay int64 `json:"doses_per_day,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// intakes
	Intakes []string `json:"intakes"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this controller schedule
func (m *ControllerSchedule) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this controller schedule based on context it is used
func (m *ControllerSchedule) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerSchedule) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerSchedule) UnmarshalBinary(b []byte) error {
	var res ControllerSchedule
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
