// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ControllerAPIError controller API error
//
// swagger:model controller.APIError
type ControllerAPIError struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this controller API error
func (m *ControllerAPIError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this controller API error based on context it is used
func (m *ControllerAPIError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ControllerAPIError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ControllerAPIError) UnmarshalBinary(b []byte) error {
	var res ControllerAPIError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
