// Code generated by go-swagger; DO NOT EDIT.

// Package restapi ikakbolit API
//
//	This is the main entry point for the Ikakbolit application, which sets up and runs the application server.
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /
//	Version: 1.0
//	Contact: Константин Троицкий<varrr7@gmail.com> https://t.me/debussy3
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
