// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infinity-ocean/ikakbolit/3-api-grpc-Homework/server/models"
)

// GetNextTakingsOKCode is the HTTP code returned for type GetNextTakingsOK
const GetNextTakingsOKCode int = 200

/*
GetNextTakingsOK OK

swagger:response getNextTakingsOK
*/
type GetNextTakingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerSchedule `json:"body,omitempty"`
}

// NewGetNextTakingsOK creates GetNextTakingsOK with default headers values
func NewGetNextTakingsOK() *GetNextTakingsOK {

	return &GetNextTakingsOK{}
}

// WithPayload adds the payload to the get next takings o k response
func (o *GetNextTakingsOK) WithPayload(payload *models.ControllerSchedule) *GetNextTakingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next takings o k response
func (o *GetNextTakingsOK) SetPayload(payload *models.ControllerSchedule) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextTakingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNextTakingsNoContentCode is the HTTP code returned for type GetNextTakingsNoContent
const GetNextTakingsNoContentCode int = 204

/*
GetNextTakingsNoContent No content

swagger:response getNextTakingsNoContent
*/
type GetNextTakingsNoContent struct {
}

// NewGetNextTakingsNoContent creates GetNextTakingsNoContent with default headers values
func NewGetNextTakingsNoContent() *GetNextTakingsNoContent {

	return &GetNextTakingsNoContent{}
}

// WriteResponse to the client
func (o *GetNextTakingsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetNextTakingsBadRequestCode is the HTTP code returned for type GetNextTakingsBadRequest
const GetNextTakingsBadRequestCode int = 400

/*
GetNextTakingsBadRequest Bad request

swagger:response getNextTakingsBadRequest
*/
type GetNextTakingsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetNextTakingsBadRequest creates GetNextTakingsBadRequest with default headers values
func NewGetNextTakingsBadRequest() *GetNextTakingsBadRequest {

	return &GetNextTakingsBadRequest{}
}

// WithPayload adds the payload to the get next takings bad request response
func (o *GetNextTakingsBadRequest) WithPayload(payload *models.ControllerAPIError) *GetNextTakingsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next takings bad request response
func (o *GetNextTakingsBadRequest) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextTakingsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNextTakingsNotFoundCode is the HTTP code returned for type GetNextTakingsNotFound
const GetNextTakingsNotFoundCode int = 404

/*
GetNextTakingsNotFound Resource not found

swagger:response getNextTakingsNotFound
*/
type GetNextTakingsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetNextTakingsNotFound creates GetNextTakingsNotFound with default headers values
func NewGetNextTakingsNotFound() *GetNextTakingsNotFound {

	return &GetNextTakingsNotFound{}
}

// WithPayload adds the payload to the get next takings not found response
func (o *GetNextTakingsNotFound) WithPayload(payload *models.ControllerAPIError) *GetNextTakingsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next takings not found response
func (o *GetNextTakingsNotFound) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextTakingsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNextTakingsInternalServerErrorCode is the HTTP code returned for type GetNextTakingsInternalServerError
const GetNextTakingsInternalServerErrorCode int = 500

/*
GetNextTakingsInternalServerError Internal server error

swagger:response getNextTakingsInternalServerError
*/
type GetNextTakingsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetNextTakingsInternalServerError creates GetNextTakingsInternalServerError with default headers values
func NewGetNextTakingsInternalServerError() *GetNextTakingsInternalServerError {

	return &GetNextTakingsInternalServerError{}
}

// WithPayload adds the payload to the get next takings internal server error response
func (o *GetNextTakingsInternalServerError) WithPayload(payload *models.ControllerAPIError) *GetNextTakingsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get next takings internal server error response
func (o *GetNextTakingsInternalServerError) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNextTakingsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
