// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infinity-ocean/ikakbolit/3-api-grpc-Homework/server/models"
)

// GetSchedulesOKCode is the HTTP code returned for type GetSchedulesOK
const GetSchedulesOKCode int = 200

/*
GetSchedulesOK OK

swagger:response getSchedulesOK
*/
type GetSchedulesOK struct {

	/*
	  In: Body
	*/
	Payload []int64 `json:"body,omitempty"`
}

// NewGetSchedulesOK creates GetSchedulesOK with default headers values
func NewGetSchedulesOK() *GetSchedulesOK {

	return &GetSchedulesOK{}
}

// WithPayload adds the payload to the get schedules o k response
func (o *GetSchedulesOK) WithPayload(payload []int64) *GetSchedulesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules o k response
func (o *GetSchedulesOK) SetPayload(payload []int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]int64, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSchedulesNoContentCode is the HTTP code returned for type GetSchedulesNoContent
const GetSchedulesNoContentCode int = 204

/*
GetSchedulesNoContent No content

swagger:response getSchedulesNoContent
*/
type GetSchedulesNoContent struct {
}

// NewGetSchedulesNoContent creates GetSchedulesNoContent with default headers values
func NewGetSchedulesNoContent() *GetSchedulesNoContent {

	return &GetSchedulesNoContent{}
}

// WriteResponse to the client
func (o *GetSchedulesNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetSchedulesBadRequestCode is the HTTP code returned for type GetSchedulesBadRequest
const GetSchedulesBadRequestCode int = 400

/*
GetSchedulesBadRequest Bad request

swagger:response getSchedulesBadRequest
*/
type GetSchedulesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetSchedulesBadRequest creates GetSchedulesBadRequest with default headers values
func NewGetSchedulesBadRequest() *GetSchedulesBadRequest {

	return &GetSchedulesBadRequest{}
}

// WithPayload adds the payload to the get schedules bad request response
func (o *GetSchedulesBadRequest) WithPayload(payload *models.ControllerAPIError) *GetSchedulesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules bad request response
func (o *GetSchedulesBadRequest) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSchedulesNotFoundCode is the HTTP code returned for type GetSchedulesNotFound
const GetSchedulesNotFoundCode int = 404

/*
GetSchedulesNotFound Resource not found

swagger:response getSchedulesNotFound
*/
type GetSchedulesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetSchedulesNotFound creates GetSchedulesNotFound with default headers values
func NewGetSchedulesNotFound() *GetSchedulesNotFound {

	return &GetSchedulesNotFound{}
}

// WithPayload adds the payload to the get schedules not found response
func (o *GetSchedulesNotFound) WithPayload(payload *models.ControllerAPIError) *GetSchedulesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules not found response
func (o *GetSchedulesNotFound) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSchedulesInternalServerErrorCode is the HTTP code returned for type GetSchedulesInternalServerError
const GetSchedulesInternalServerErrorCode int = 500

/*
GetSchedulesInternalServerError Internal server error

swagger:response getSchedulesInternalServerError
*/
type GetSchedulesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetSchedulesInternalServerError creates GetSchedulesInternalServerError with default headers values
func NewGetSchedulesInternalServerError() *GetSchedulesInternalServerError {

	return &GetSchedulesInternalServerError{}
}

// WithPayload adds the payload to the get schedules internal server error response
func (o *GetSchedulesInternalServerError) WithPayload(payload *models.ControllerAPIError) *GetSchedulesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedules internal server error response
func (o *GetSchedulesInternalServerError) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSchedulesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
