// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/infinity-ocean/ikakbolit/3-api-grpc-Homework/server/models"
)

// GetScheduleOKCode is the HTTP code returned for type GetScheduleOK
const GetScheduleOKCode int = 200

/*
GetScheduleOK OK

swagger:response getScheduleOK
*/
type GetScheduleOK struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerSchedule `json:"body,omitempty"`
}

// NewGetScheduleOK creates GetScheduleOK with default headers values
func NewGetScheduleOK() *GetScheduleOK {

	return &GetScheduleOK{}
}

// WithPayload adds the payload to the get schedule o k response
func (o *GetScheduleOK) WithPayload(payload *models.ControllerSchedule) *GetScheduleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule o k response
func (o *GetScheduleOK) SetPayload(payload *models.ControllerSchedule) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetScheduleNoContentCode is the HTTP code returned for type GetScheduleNoContent
const GetScheduleNoContentCode int = 204

/*
GetScheduleNoContent No content

swagger:response getScheduleNoContent
*/
type GetScheduleNoContent struct {
}

// NewGetScheduleNoContent creates GetScheduleNoContent with default headers values
func NewGetScheduleNoContent() *GetScheduleNoContent {

	return &GetScheduleNoContent{}
}

// WriteResponse to the client
func (o *GetScheduleNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// GetScheduleBadRequestCode is the HTTP code returned for type GetScheduleBadRequest
const GetScheduleBadRequestCode int = 400

/*
GetScheduleBadRequest Bad request

swagger:response getScheduleBadRequest
*/
type GetScheduleBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetScheduleBadRequest creates GetScheduleBadRequest with default headers values
func NewGetScheduleBadRequest() *GetScheduleBadRequest {

	return &GetScheduleBadRequest{}
}

// WithPayload adds the payload to the get schedule bad request response
func (o *GetScheduleBadRequest) WithPayload(payload *models.ControllerAPIError) *GetScheduleBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule bad request response
func (o *GetScheduleBadRequest) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetScheduleNotFoundCode is the HTTP code returned for type GetScheduleNotFound
const GetScheduleNotFoundCode int = 404

/*
GetScheduleNotFound Resource not found

swagger:response getScheduleNotFound
*/
type GetScheduleNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetScheduleNotFound creates GetScheduleNotFound with default headers values
func NewGetScheduleNotFound() *GetScheduleNotFound {

	return &GetScheduleNotFound{}
}

// WithPayload adds the payload to the get schedule not found response
func (o *GetScheduleNotFound) WithPayload(payload *models.ControllerAPIError) *GetScheduleNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule not found response
func (o *GetScheduleNotFound) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetScheduleInternalServerErrorCode is the HTTP code returned for type GetScheduleInternalServerError
const GetScheduleInternalServerErrorCode int = 500

/*
GetScheduleInternalServerError Internal server error

swagger:response getScheduleInternalServerError
*/
type GetScheduleInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ControllerAPIError `json:"body,omitempty"`
}

// NewGetScheduleInternalServerError creates GetScheduleInternalServerError with default headers values
func NewGetScheduleInternalServerError() *GetScheduleInternalServerError {

	return &GetScheduleInternalServerError{}
}

// WithPayload adds the payload to the get schedule internal server error response
func (o *GetScheduleInternalServerError) WithPayload(payload *models.ControllerAPIError) *GetScheduleInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get schedule internal server error response
func (o *GetScheduleInternalServerError) SetPayload(payload *models.ControllerAPIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetScheduleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
