// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostScheduleHandlerFunc turns a function with the right signature into a post schedule handler
type PostScheduleHandlerFunc func(PostScheduleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostScheduleHandlerFunc) Handle(params PostScheduleParams) middleware.Responder {
	return fn(params)
}

// PostScheduleHandler interface for that can handle valid post schedule params
type PostScheduleHandler interface {
	Handle(PostScheduleParams) middleware.Responder
}

// NewPostSchedule creates a new http.Handler for the post schedule operation
func NewPostSchedule(ctx *middleware.Context, handler PostScheduleHandler) *PostSchedule {
	return &PostSchedule{Context: ctx, Handler: handler}
}

/*
	PostSchedule swagger:route POST /schedule postSchedule

Add a new schedule [! Предпочтительнее использовать http-клиент для post-запросов, например Postman]

Create a new schedule for a user
*/
type PostSchedule struct {
	Context *middleware.Context
	Handler PostScheduleHandler
}

func (o *PostSchedule) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostScheduleParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
