basePath: /
definitions:
  controller.APIError:
    properties:
      message:
        type: string
    type: object
  controller.Schedule:
    properties:
      created_at:
        type: string
      cure_name:
        type: string
      doses_per_day:
        type: integer
      duration:
        type: integer
      id:
        type: integer
      intakes:
        items:
          type: string
        type: array
      user_id:
        type: integer
    type: object
  controller.responseScheduleID:
    properties:
      schedule_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: varrr7@gmail.com
    name: Константин Троицкий
    url: https://t.me/debussy3
  description: This is the main entry point for the Ikakbolit application, which sets
    up and runs the application server.
  title: ikakbolit API
  version: "1.0"
paths:
  /next_takings:
    get:
      description: Retrieve upcoming medication schedules for a user
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Schedule'
        "204":
          description: No content
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Resource not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get next scheduled takings
  /schedule:
    get:
      description: Retrieve a schedule by user ID and schedule ID
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      - description: Schedule ID
        in: query
        name: schedule_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Schedule'
        "204":
          description: No content
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Resource not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get a specific schedule
    post:
      consumes:
      - application/json
      description: Create a new schedule for a user
      parameters:
      - description: Schedule data
        in: body
        name: schedule
        required: true
        schema:
          $ref: '#/definitions/controller.Schedule'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controller.responseScheduleID'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Resource not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Add a new schedule [! Предпочтительнее использовать http-клиент для
        post-запросов, например Postman]
  /schedules:
    get:
      description: Retrieve schedule IDs for a given user
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "204":
          description: No content
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/controller.APIError'
        "404":
          description: Resource not found
          schema:
            $ref: '#/definitions/controller.APIError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/controller.APIError'
      summary: Get user schedules
swagger: "2.0"
